apiVersion: apps/v1
kind: Deployment
metadata:
  name: sba-app
spec:
  selector:
    matchLabels:
      app: flaskapp
  replicas: 3 
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: sba-app
        image: sumanth55/sba-app:v1
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: sba-app-service
spec:
  type: NodePort
  selector:
    app: sba-app
  ports:
  - protocol: "TCP"
    port: 8090
    targetPort: 8090
    